const types = {
    GET_COURSES: 'GET_COURSES',
    RENAME_COURSE_TITLE: 'RENAME_COURSE_TITLE',
    RENAME_COURSE_DESCRIPTION: 'RENAME_COURSE_DESCRIPTION',
    RENAME_UNIT_TITLE: 'RENAME_UNIT_TITLE',
    RENAME_UNIT_DESCRIPTION: 'RENAME_UNIT_DESCRIPTION',
    DELETE_UNIT: 'DELETE_UNIT',
    CREATE_NEW_UNIT: 'CREATE_NEW_UNIT',
    MOVE_MODULE_UP: 'MOVE_MODULE_UP',
    MOVE_MODULE_DOWN: 'MOVE_MODULE_DOWN',
    CREATE_NEW_MODULE: 'CREATE_NEW_MODULE',
    DELETE_MODULE: 'DELETE_MODULE'
}

export default types;